---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suginami
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn